name: minetest
version: 5.8.0

summary: Open source voxel game engine
description: |
  Minetest is a minecraft-inspired game written from scratch and licensed under the LGPL (version 2.1 or later). It supports both survival and creative modes along with multiplayer support, dynamic lighting, and an "infinite" map generator.

  **Authors**

  This snap package is maintained by the Snapcrafters community. It is not necessarily endorsed or officially supported by the developers of the application itself.

license: LGPL-2.1-or-later
website: https://www.minetest.net/
contact: https://github.com/snapcrafters/minetest/issues
issues: https://github.com/snapcrafters/minetest/issues
source-code: https://github.com/snapcrafters/minetest
icon: snap/gui/minetest.svg

base: core22
compression: lzo
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: i386
  - build-on: arm64

apps:
  minetest:
    environment:
      HOME: "$SNAP_USER_COMMON"
    command: bin/launcher
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - network
      - network-bind
      - opengl
      - pulseaudio
      - removable-media
      - x11

parts:
  launcher:
    plugin: dump
    source: ./snap/local
    source-type: local

  minetestgame:
    source: https://github.com/minetest/minetest_game.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    plugin: dump
    organize:
      "*": "share/minetest/games/minetest_game/"

  minetest:
    plugin: cmake
    source: https://github.com/minetest/minetest.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DRUN_IN_PLACE=FALSE
    override-pull: |
      craftctl default
      git clone --depth=1 --branch=1.9.0mt13 https://github.com/minetest/irrlicht lib/irrlichtmt
    build-packages:
      - cmake
      - g++
      - gcc
      - gettext
      - imagemagick
      - libbz2-dev
      - libcurl4-gnutls-dev
      - libfreetype6-dev
      - libglu1-mesa-dev
      - libjpeg-dev
      - libjsoncpp-dev
      - libleveldb-dev
      - libluajit-5.1-dev
      - libogg-dev
      - libopenal-dev
      - libpng-dev
      - libpulse-dev
      - libsdl2-dev
      - libsqlite3-dev
      - libvorbis-dev
      - libx11-dev
      - libzstd-dev
      - zlib1g-dev
    stage-packages:
      - libcurl3-gnutls
      - libfreetype6
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libjpeg-turbo8
      - libjsoncpp25
      - libleveldb1d
      - libluajit-5.1-2
      - libopenal1
      - libopengl0
      - libpng16-16
      - libpulse0
      - libsnappy1v5
      - libvorbisfile3
      - libx11-6
      - libx11-xcb1
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-glx0
      - libxcb-present0
      - libxcb-sync1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxi6
      - libxshmfence1
      - libxxf86vm1
      - libzstd1
